### ISSUE TITLE
Composer install falling

### ISSUE THREAD

**Issue by amandiobm** [carmino-app/envault-docker#1]
When running `docker-compose up envault`, upon building the image I got this error

```
#19 0.565 Installing dependencies from lock file (including require-dev)
#19 0.571 Verifying lock file contents can be installed on current platform.
#19 0.587 Your lock file does not contain a compatible set of packages. Please run composer update.
#19 0.587
#19 0.587   Problem 1
#19 0.587     - phpspec/prophecy is locked to version 1.12.2 and an update of this package was not requested.
#19 0.587     - phpspec/prophecy 1.12.2 requires php ^7.2 || ~8.0, <8.1 -> your php version (8.1.1) does not satisfy that requirement.
#19 0.587   Problem 2
#19 0.587     - phpspec/prophecy 1.12.2 requires php ^7.2 || ~8.0, <8.1 -> your php version (8.1.1) does not satisfy that requirement.
#19 0.587     - phpunit/phpunit 9.5.0 requires phpspec/prophecy ^1.12.1 -> satisfiable by phpspec/prophecy[1.12.2].
#19 0.587     - phpunit/phpunit is locked to version 9.5.0 and an update of this package was not requested.
#19 0.587
```

My solution was to remove `composer.lock` from the package.
`RUN rm composer.lock`

after that was a walk in the park!

tks for this!

I also did on change to always install the latest version of envault

```
RUN curl -L $(curl -s https://api.github.com/repos/envault/envault/releases/latest | grep tarball_url | cut -d '"' -f 4) -o latest.tar.gz
RUN tar -xvzf latest.tar.gz --strip 1
```

don't know if could be better, but, is working ;D

**Comment by bencehornak** [comment]
Hey @amandiobm, thanks for reaching out!

It's the envault project, which owns the `composer.lock` file, so the fix in this case can be done on the envault project, not here. Feel free to open a similar issue there. Unfortunately though, the envault project doesn't seem to be maintained any more, as their latest release is dated back to June 2020.

An alternative to envault can be [Dotenv Sync](https://sync.dotenv.org/), a pretty new service which you can request early access to, but I haven't tried it out myself, just came across this recently.
